---
on:
  push:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  terraform:
    uses: "Mosher-Labs/.github/.github/workflows/terraform.yml@main"
    secrets: inherit
    with:
      enable_apply: ${{ github.ref == 'refs/heads/main' && true || false }}
