---
on:
  push:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  ci:
    uses: "Mosher-Labs/.github/.github/workflows/terraform.yml@feat-add-terraform-plan"
    secrets:
      HEIMDALLR_TOKEN: ${{ secrets.HEIMDALLR_TOKEN }}
