---
on:
  push:

jobs:
  ci:
    uses: "Mosher-Labs/.github/.github/workflows/terraform.yml@v0.9.0"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    secrets:
      HEIMDALLR_TOKEN: ${{ secrets.HEIMDALLR_TOKEN }}
